// packages/vue/src/components/ChatWidget.vue
<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue';
import type { OpenClawClientOptions, Message } from 'openclaw-webchat';
import { useOpenClawChat } from '../composables/useOpenClawChat';
import { getOrCreateStableSessionKey } from './sessionKey';

export interface ChatWidgetAuthTexts {
  pairingRequiredTitle?: string;
  pairingRequiredBody?: string;
  scopeMissingWriteTitle?: string;
  scopeMissingWriteBody?: string;
  retryConnectionButton?: string;
  retryingConnectionButton?: string;
}

export interface ChatWidgetProps {
  // OpenClawClientOptions - explicitly defined for Vue props
  gateway: string;
  token?: string;
  password?: string;
  deviceToken?: string;
  clientName?: string;
  clientVersion?: string;
  reconnect?: boolean;
  reconnectInterval?: number;
  maxReconnectAttempts?: number;
  connectionTimeout?: number;
  debug?: boolean;
  sessionKey?: string;
  // Widget-specific options
  position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left' | 'inline';
  theme?: 'light' | 'dark' | 'auto';
  title?: string;
  placeholder?: string;
  defaultOpen?: boolean;
  autoConnect?: boolean;
  authTexts?: ChatWidgetAuthTexts;
}

const props = withDefaults(defineProps<ChatWidgetProps>(), {
  position: 'bottom-right',
  theme: 'light',
  title: 'AI Assistant',
  placeholder: 'Type a message...',
  defaultOpen: false,
  autoConnect: true,
});

const emit = defineEmits<{
  send: [content: string];
  message: [message: Message];
}>();

defineSlots<{
  message?: (props: { message: Message }) => unknown;
  loading?: (props: { content: string }) => unknown;
}>();

const isOpen = ref(props.defaultOpen);
const input = ref('');
const messagesEndRef = ref<HTMLDivElement | null>(null);
const resolvedSessionKey = props.sessionKey || getOrCreateStableSessionKey();

// Explicitly construct client options from props, filtering out undefined values
const clientOptions: OpenClawClientOptions & { autoConnect?: boolean } = Object.fromEntries(
  Object.entries({
    gateway: props.gateway,
    token: props.token,
    password: props.password,
    deviceToken: props.deviceToken,
    clientName: props.clientName,
    clientVersion: props.clientVersion,
    reconnect: props.reconnect,
    reconnectInterval: props.reconnectInterval,
    maxReconnectAttempts: props.maxReconnectAttempts,
    connectionTimeout: props.connectionTimeout,
    debug: props.debug,
    sessionKey: resolvedSessionKey,
    autoConnect: props.autoConnect,
  }).filter(([_, v]) => v !== undefined)
) as OpenClawClientOptions & { autoConnect?: boolean };

const {
  messages,
  isConnected,
  isLoading,
  streamingContent,
  error,
  connect,
  send: clientSend,
} = useOpenClawChat(clientOptions);
const isRetryingConnect = ref(false);
const authIssue = computed(() => {
  const code = (error.value as { code?: string } | null)?.code;
  if (code === 'PAIRING_REQUIRED') {
    return 'pairing_required';
  }
  if (code === 'SCOPE_MISSING_WRITE') {
    return 'scope_missing_write';
  }
  return 'none';
});
const resolvedAuthTexts = computed<Required<ChatWidgetAuthTexts>>(() => ({
  pairingRequiredTitle: props.authTexts?.pairingRequiredTitle ?? 'Pairing Required',
  pairingRequiredBody:
    props.authTexts?.pairingRequiredBody ?? 'Approve this device on gateway host, then retry connection.',
  scopeMissingWriteTitle: props.authTexts?.scopeMissingWriteTitle ?? 'Permission Required',
  scopeMissingWriteBody:
    props.authTexts?.scopeMissingWriteBody ??
    'This device is missing operator.write. Ask an administrator to grant write scope, then retry connection.',
  retryConnectionButton: props.authTexts?.retryConnectionButton ?? 'Retry Connection',
  retryingConnectionButton: props.authTexts?.retryingConnectionButton ?? 'Retrying...',
}));

const themes = {
  light: {
    bg: '#ffffff',
    headerBg: '#f8f9fa',
    headerBorder: '#e9ecef',
    userBg: '#007bff',
    userColor: '#ffffff',
    aiBg: '#f1f3f4',
    aiColor: '#1a1a1a',
    inputBg: '#ffffff',
    inputBorder: '#dee2e6',
    buttonBg: '#007bff',
    buttonColor: '#ffffff',
  },
  dark: {
    bg: '#1a1a1a',
    headerBg: '#2d2d2d',
    headerBorder: '#404040',
    userBg: '#0066cc',
    userColor: '#ffffff',
    aiBg: '#2d2d2d',
    aiColor: '#ffffff',
    inputBg: '#2d2d2d',
    inputBorder: '#404040',
    buttonBg: '#0066cc',
    buttonColor: '#ffffff',
  },
};

const resolvedTheme = computed(() => {
  if (props.theme === 'auto') {
    return typeof window !== 'undefined' &&
      window.matchMedia('(prefers-color-scheme: dark)').matches
      ? 'dark'
      : 'light';
  }
  return props.theme;
});

const colors = computed(() => themes[resolvedTheme.value]);

const positionStyles = computed(() => {
  const positions = {
    'bottom-right': { bottom: '20px', right: '20px' },
    'bottom-left': { bottom: '20px', left: '20px' },
    'top-right': { top: '20px', right: '20px' },
    'top-left': { top: '20px', left: '20px' },
    inline: {},
  };
  return positions[props.position];
});

watch(
  [messages, streamingContent],
  () => {
    nextTick(() => {
      messagesEndRef.value?.scrollIntoView({ behavior: 'smooth' });
    });
  },
  { deep: true }
);

watch(
  () => messages.value.length,
  (newLen, oldLen) => {
    if (newLen > oldLen) {
      emit('message', messages.value[newLen - 1]);
    }
  }
);

async function handleSend() {
  if (!input.value.trim() || !isConnected.value || isLoading.value) return;

  const content = input.value.trim();
  input.value = '';
  emit('send', content);

  try {
    await clientSend(content);
  } catch (err) {
    console.error('Failed to send message:', err);
  }
}

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    handleSend();
  }
}

async function handleRetryConnection() {
  if (isRetryingConnect.value) return;
  isRetryingConnect.value = true;
  try {
    await connect();
  } finally {
    isRetryingConnect.value = false;
  }
}
</script>

<template>
  <!-- Inline mode -->
  <div
    v-if="position === 'inline'"
    class="openclaw-widget"
    :style="{ backgroundColor: colors.bg }"
  >
    <div class="openclaw-messages">
      <template v-for="msg in messages" :key="msg.id">
        <slot name="message" :message="msg">
          <div
            class="openclaw-message"
            :style="{
              backgroundColor: msg.role === 'user' ? colors.userBg : colors.aiBg,
              color: msg.role === 'user' ? colors.userColor : colors.aiColor,
              marginLeft: msg.role === 'user' ? 'auto' : '0',
              marginRight: msg.role === 'user' ? '0' : 'auto',
            }"
          >
            {{ msg.content }}
          </div>
        </slot>
      </template>
      <template v-if="isLoading">
        <slot name="loading" :content="streamingContent">
          <div
            class="openclaw-message"
            :style="{
              backgroundColor: colors.aiBg,
              color: colors.aiColor,
              opacity: 0.8,
            }"
          >
            {{ streamingContent || '...' }}
          </div>
        </slot>
      </template>
      <div v-if="authIssue !== 'none'" class="openclaw-pairing">
        <div class="openclaw-pairing-title">
          {{ authIssue === 'pairing_required' ? resolvedAuthTexts.pairingRequiredTitle : resolvedAuthTexts.scopeMissingWriteTitle }}
        </div>
        <div class="openclaw-pairing-text">
          {{ authIssue === 'pairing_required' ? resolvedAuthTexts.pairingRequiredBody : resolvedAuthTexts.scopeMissingWriteBody }}
        </div>
        <button
          @click="handleRetryConnection"
          :disabled="isRetryingConnect"
          :style="{
            backgroundColor: colors.buttonBg,
            color: colors.buttonColor,
            opacity: isRetryingConnect ? 0.6 : 1,
          }"
        >
          {{ isRetryingConnect ? resolvedAuthTexts.retryingConnectionButton : resolvedAuthTexts.retryConnectionButton }}
        </button>
      </div>
      <div v-if="error" class="openclaw-error">
        Error: {{ error.message }}
      </div>
      <div ref="messagesEndRef" />
    </div>
    <div class="openclaw-input" :style="{ borderColor: colors.headerBorder }">
      <input
        type="text"
        v-model="input"
        @keydown="handleKeyDown"
        :placeholder="isConnected ? placeholder : 'Connecting...'"
        :disabled="!isConnected || isLoading"
        :style="{
          backgroundColor: colors.inputBg,
          borderColor: colors.inputBorder,
          color: colors.aiColor,
        }"
      />
      <button
        @click="handleSend"
        :disabled="!isConnected || isLoading || !input.trim()"
        :style="{
          backgroundColor: colors.buttonBg,
          color: colors.buttonColor,
          opacity: !isConnected || isLoading || !input.trim() ? 0.5 : 1,
        }"
      >
        Send
      </button>
    </div>
  </div>

  <!-- Floating mode -->
  <div
    v-else
    class="openclaw-container"
    :style="positionStyles"
  >
    <div
      v-if="isOpen"
      class="openclaw-widget"
      :style="{ backgroundColor: colors.bg }"
    >
      <div
        class="openclaw-header"
        :style="{
          backgroundColor: colors.headerBg,
          borderColor: colors.headerBorder,
        }"
      >
        <span>{{ title }}</span>
        <button
          @click="isOpen = false"
          class="openclaw-close"
          :style="{ color: colors.aiColor }"
        >
          ×
        </button>
      </div>
      <div class="openclaw-messages">
        <template v-for="msg in messages" :key="msg.id">
          <slot name="message" :message="msg">
            <div
              class="openclaw-message"
              :style="{
                backgroundColor: msg.role === 'user' ? colors.userBg : colors.aiBg,
                color: msg.role === 'user' ? colors.userColor : colors.aiColor,
                marginLeft: msg.role === 'user' ? 'auto' : '0',
                marginRight: msg.role === 'user' ? '0' : 'auto',
              }"
            >
              {{ msg.content }}
            </div>
          </slot>
        </template>
        <template v-if="isLoading">
          <slot name="loading" :content="streamingContent">
            <div
              class="openclaw-message"
              :style="{
                backgroundColor: colors.aiBg,
                color: colors.aiColor,
                opacity: 0.8,
              }"
            >
              {{ streamingContent || '...' }}
            </div>
          </slot>
        </template>
        <div v-if="authIssue !== 'none'" class="openclaw-pairing">
          <div class="openclaw-pairing-title">
            {{ authIssue === 'pairing_required' ? resolvedAuthTexts.pairingRequiredTitle : resolvedAuthTexts.scopeMissingWriteTitle }}
          </div>
          <div class="openclaw-pairing-text">
            {{ authIssue === 'pairing_required' ? resolvedAuthTexts.pairingRequiredBody : resolvedAuthTexts.scopeMissingWriteBody }}
          </div>
          <button
            @click="handleRetryConnection"
            :disabled="isRetryingConnect"
            :style="{
              backgroundColor: colors.buttonBg,
              color: colors.buttonColor,
              opacity: isRetryingConnect ? 0.6 : 1,
            }"
          >
            {{ isRetryingConnect ? resolvedAuthTexts.retryingConnectionButton : resolvedAuthTexts.retryConnectionButton }}
          </button>
        </div>
        <div v-if="error" class="openclaw-error">
          Error: {{ error.message }}
        </div>
        <div ref="messagesEndRef" />
      </div>
      <div class="openclaw-input" :style="{ borderColor: colors.headerBorder }">
        <input
          type="text"
          v-model="input"
          @keydown="handleKeyDown"
          :placeholder="isConnected ? placeholder : 'Connecting...'"
          :disabled="!isConnected || isLoading"
          :style="{
            backgroundColor: colors.inputBg,
            borderColor: colors.inputBorder,
            color: colors.aiColor,
          }"
        />
        <button
          @click="handleSend"
          :disabled="!isConnected || isLoading || !input.trim()"
          :style="{
            backgroundColor: colors.buttonBg,
            color: colors.buttonColor,
            opacity: !isConnected || isLoading || !input.trim() ? 0.5 : 1,
          }"
        >
          Send
        </button>
      </div>
    </div>
    <button
      v-else
      @click="isOpen = true"
      class="openclaw-toggle"
      :style="{
        backgroundColor: colors.buttonBg,
        color: colors.buttonColor,
      }"
    >
      💬
    </button>
  </div>
</template>

<style scoped>
.openclaw-container {
  position: fixed;
  z-index: 9999;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.openclaw-widget {
  width: 380px;
  height: 500px;
  border-radius: 12px;
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.openclaw-header {
  padding: 16px 20px;
  font-weight: 600;
  font-size: 16px;
  border-bottom: 1px solid;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.openclaw-close {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 20px;
}

.openclaw-messages {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}

.openclaw-message {
  margin-bottom: 12px;
  padding: 10px 14px;
  border-radius: 12px;
  max-width: 80%;
  word-break: break-word;
}

.openclaw-error {
  color: #dc3545;
  padding: 8px 12px;
  font-size: 14px;
}

.openclaw-pairing {
  margin-bottom: 12px;
  padding: 10px 12px;
  border-radius: 8px;
  border: 1px solid #f0c2c2;
  background: #fff7f7;
}

.openclaw-pairing-title {
  color: #9f2f2f;
  font-weight: 600;
  font-size: 13px;
  margin-bottom: 6px;
}

.openclaw-pairing-text {
  color: #5f3b3b;
  font-size: 13px;
  margin-bottom: 8px;
}

.openclaw-pairing button {
  padding: 10px 16px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
}

.openclaw-input {
  display: flex;
  padding: 12px;
  border-top: 1px solid;
  gap: 8px;
}

.openclaw-input input {
  flex: 1;
  padding: 10px 14px;
  border-radius: 8px;
  border: 1px solid;
  font-size: 14px;
  outline: none;
}

.openclaw-input button {
  padding: 10px 16px;
  border-radius: 8px;
  border: none;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
}

.openclaw-toggle {
  width: 56px;
  height: 56px;
  border-radius: 28px;
  border: none;
  cursor: pointer;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
}
</style>

// packages/react/src/components/ChatWidget.tsx
import React, { useState, useRef, useEffect } from 'react';
import type { OpenClawClientOptions, Message } from 'openclaw-webchat';
import { useOpenClawChat } from '../hooks/useOpenClawChat';
import { getOrCreateStableSessionKey } from './sessionKey';

export interface ChatWidgetAuthTexts {
  pairingRequiredTitle?: string;
  pairingRequiredBody?: string;
  scopeMissingWriteTitle?: string;
  scopeMissingWriteBody?: string;
  retryConnectionButton?: string;
  retryingConnectionButton?: string;
}

export interface ChatWidgetProps extends OpenClawClientOptions {
  /** Widget position */
  position?: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left' | 'inline';

  /** Theme */
  theme?: 'light' | 'dark' | 'auto';

  /** Widget title */
  title?: string;

  /** Placeholder text for input */
  placeholder?: string;

  /** Initial open state */
  defaultOpen?: boolean;

  /** Custom styles */
  className?: string;

  /** Custom message renderer */
  renderMessage?: (message: Message) => React.ReactNode;

  /** Custom loading indicator */
  renderLoading?: (streamingContent: string) => React.ReactNode;

  /** On send callback */
  onSend?: (content: string) => void;

  /** On message received callback */
  onMessage?: (message: Message) => void;

  /** Override auth issue copy in widget UI */
  authTexts?: ChatWidgetAuthTexts;
}

const defaultStyles = {
  container: {
    position: 'fixed' as const,
    zIndex: 9999,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  positions: {
    'bottom-right': { bottom: 20, right: 20 },
    'bottom-left': { bottom: 20, left: 20 },
    'top-right': { top: 20, right: 20 },
    'top-left': { top: 20, left: 20 },
    inline: { position: 'relative' as const },
  },
  widget: {
    width: 380,
    height: 500,
    borderRadius: 12,
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.15)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  header: {
    padding: '16px 20px',
    fontWeight: 600,
    fontSize: 16,
    borderBottom: '1px solid',
  },
  messages: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: 16,
  },
  message: {
    marginBottom: 12,
    padding: '10px 14px',
    borderRadius: 12,
    maxWidth: '80%',
    wordBreak: 'break-word' as const,
  },
  input: {
    display: 'flex',
    padding: 12,
    borderTop: '1px solid',
    gap: 8,
  },
  inputField: {
    flex: 1,
    padding: '10px 14px',
    borderRadius: 8,
    border: '1px solid',
    fontSize: 14,
    outline: 'none',
  },
  sendButton: {
    padding: '10px 16px',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
  },
  toggleButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 24,
  },
};

const themes = {
  light: {
    bg: '#ffffff',
    headerBg: '#f8f9fa',
    headerBorder: '#e9ecef',
    userBg: '#007bff',
    userColor: '#ffffff',
    aiBg: '#f1f3f4',
    aiColor: '#1a1a1a',
    inputBg: '#ffffff',
    inputBorder: '#dee2e6',
    buttonBg: '#007bff',
    buttonColor: '#ffffff',
  },
  dark: {
    bg: '#1a1a1a',
    headerBg: '#2d2d2d',
    headerBorder: '#404040',
    userBg: '#0066cc',
    userColor: '#ffffff',
    aiBg: '#2d2d2d',
    aiColor: '#ffffff',
    inputBg: '#2d2d2d',
    inputBorder: '#404040',
    buttonBg: '#0066cc',
    buttonColor: '#ffffff',
  },
};

/**
 * Ready-to-use Chat Widget component
 *
 * @example
 * ```tsx
 * <ChatWidget
 *   gateway="wss://ai.example.com:18789"
 *   token="your-token"
 *   position="bottom-right"
 *   theme="light"
 *   title="AI Assistant"
 * />
 * ```
 */
export function ChatWidget({
  position = 'bottom-right',
  theme = 'light',
  title = 'AI Assistant',
  placeholder = 'Type a message...',
  defaultOpen = false,
  className,
  renderMessage,
  renderLoading,
  onSend,
  onMessage,
  authTexts,
  ...clientOptions
}: ChatWidgetProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  const [input, setInput] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const resolvedSessionKey = clientOptions.sessionKey ?? getOrCreateStableSessionKey();
  const resolvedClientOptions = {
    ...clientOptions,
    sessionKey: resolvedSessionKey,
  };

  const {
    messages,
    isConnected,
    isLoading,
    streamingContent,
    error,
    send,
    connect,
  } = useOpenClawChat(resolvedClientOptions);
  const [isRetryingConnect, setIsRetryingConnect] = useState(false);
  const resolvedAuthTexts: Required<ChatWidgetAuthTexts> = {
    pairingRequiredTitle: authTexts?.pairingRequiredTitle ?? 'Pairing Required',
    pairingRequiredBody:
      authTexts?.pairingRequiredBody ?? 'Approve this device on gateway host, then retry connection.',
    scopeMissingWriteTitle: authTexts?.scopeMissingWriteTitle ?? 'Permission Required',
    scopeMissingWriteBody:
      authTexts?.scopeMissingWriteBody ??
      'This device is missing operator.write. Ask an administrator to grant write scope, then retry connection.',
    retryConnectionButton: authTexts?.retryConnectionButton ?? 'Retry Connection',
    retryingConnectionButton: authTexts?.retryingConnectionButton ?? 'Retrying...',
  };

  // Get current theme colors
  const resolvedTheme = theme === 'auto'
    ? (typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
    : theme;
  const colors = themes[resolvedTheme];

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, streamingContent]);

  // Notify on new messages
  useEffect(() => {
    if (messages.length > 0 && onMessage) {
      onMessage(messages[messages.length - 1]);
    }
  }, [messages.length]);

  const handleSend = async () => {
    if (!input.trim() || !isConnected || isLoading) return;

    const content = input.trim();
    setInput('');
    onSend?.(content);

    try {
      await send(content);
    } catch (err) {
      console.error('Failed to send message:', err);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const renderDefaultMessage = (message: Message) => (
    <div
      key={message.id}
      style={{
        ...defaultStyles.message,
        backgroundColor: message.role === 'user' ? colors.userBg : colors.aiBg,
        color: message.role === 'user' ? colors.userColor : colors.aiColor,
        marginLeft: message.role === 'user' ? 'auto' : 0,
        marginRight: message.role === 'user' ? 0 : 'auto',
      }}
    >
      {message.content}
    </div>
  );

  const renderDefaultLoading = (content: string) => (
    <div
      style={{
        ...defaultStyles.message,
        backgroundColor: colors.aiBg,
        color: colors.aiColor,
        opacity: 0.8,
      }}
    >
      {content || '...'}
    </div>
  );

  const errorCode = (error as { code?: string } | null)?.code;
  const authIssue = errorCode === 'PAIRING_REQUIRED'
    ? 'pairing_required'
    : errorCode === 'SCOPE_MISSING_WRITE'
      ? 'scope_missing_write'
      : 'none';

  const handleRetryConnection = async () => {
    if (isRetryingConnect) return;
    setIsRetryingConnect(true);
    try {
      await connect();
    } finally {
      setIsRetryingConnect(false);
    }
  };

  // Inline mode - render directly
  if (position === 'inline') {
    return (
      <div
        className={className}
        style={{
          ...defaultStyles.widget,
          backgroundColor: colors.bg,
        }}
      >
        {renderChatContent()}
      </div>
    );
  }

  // Floating mode
  return (
    <div
      className={className}
      style={{
        ...defaultStyles.container,
        ...defaultStyles.positions[position],
      }}
    >
      {isOpen ? (
        <div
          style={{
            ...defaultStyles.widget,
            backgroundColor: colors.bg,
          }}
        >
          {/* Header */}
          <div
            style={{
              ...defaultStyles.header,
              backgroundColor: colors.headerBg,
              borderColor: colors.headerBorder,
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            <span>{title}</span>
            <button
              onClick={() => setIsOpen(false)}
              style={{
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                fontSize: 20,
                color: colors.aiColor,
              }}
            >
              ×
            </button>
          </div>

          {renderChatContent()}
        </div>
      ) : (
        <button
          onClick={() => setIsOpen(true)}
          style={{
            ...defaultStyles.toggleButton,
            backgroundColor: colors.buttonBg,
            color: colors.buttonColor,
          }}
        >
          💬
        </button>
      )}
    </div>
  );

  function renderChatContent() {
    return (
      <>
        {/* Messages */}
        <div style={defaultStyles.messages}>
          {messages.map((msg) =>
            renderMessage ? renderMessage(msg) : renderDefaultMessage(msg)
          )}
          {isLoading && (
            renderLoading
              ? renderLoading(streamingContent)
              : renderDefaultLoading(streamingContent)
          )}
          {authIssue !== 'none' && (
            <div
              style={{
                marginBottom: 12,
                padding: '10px 12px',
                borderRadius: 8,
                border: '1px solid #f0c2c2',
                background: '#fff7f7',
              }}
            >
              <div style={{ color: '#9f2f2f', fontWeight: 600, fontSize: 13, marginBottom: 6 }}>
                {authIssue === 'pairing_required'
                  ? resolvedAuthTexts.pairingRequiredTitle
                  : resolvedAuthTexts.scopeMissingWriteTitle}
              </div>
              <div style={{ color: '#5f3b3b', fontSize: 13, marginBottom: 8 }}>
                {authIssue === 'pairing_required'
                  ? resolvedAuthTexts.pairingRequiredBody
                  : resolvedAuthTexts.scopeMissingWriteBody}
              </div>
              <button
                onClick={() => void handleRetryConnection()}
                disabled={isRetryingConnect}
                style={{
                  ...defaultStyles.sendButton,
                  backgroundColor: colors.buttonBg,
                  color: colors.buttonColor,
                  opacity: isRetryingConnect ? 0.6 : 1,
                }}
              >
                {isRetryingConnect
                  ? resolvedAuthTexts.retryingConnectionButton
                  : resolvedAuthTexts.retryConnectionButton}
              </button>
            </div>
          )}
          {error && (
            <div style={{ color: '#dc3545', padding: '8px 12px', fontSize: 14 }}>
              Error: {error.message}
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div
          style={{
            ...defaultStyles.input,
            borderColor: colors.headerBorder,
          }}
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={isConnected ? placeholder : 'Connecting...'}
            disabled={!isConnected || isLoading}
            style={{
              ...defaultStyles.inputField,
              backgroundColor: colors.inputBg,
              borderColor: colors.inputBorder,
              color: colors.aiColor,
            }}
          />
          <button
            onClick={handleSend}
            disabled={!isConnected || isLoading || !input.trim()}
            style={{
              ...defaultStyles.sendButton,
              backgroundColor: colors.buttonBg,
              color: colors.buttonColor,
              opacity: !isConnected || isLoading || !input.trim() ? 0.5 : 1,
            }}
          >
            Send
          </button>
        </div>
      </>
    );
  }
}
